baseURL = "https://www.fossgis.de/"
title = "FOSSGIS"
theme = "fossgis"

languageCode = "de-de"
defaultContentLanguage = "de"

sectionPagesMenu = "main"

enableGitInfo = true

disableKinds = ['taxonomy', 'term']

[markup.goldmark.renderer]
unsafe= true # allow inline HTML

[outputs]
home = ['html']
section = ['html']

